# Generated by Django 4.1.2 on 2022-11-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserdata',
            name='otp_secret',
            field=models.CharField(default='', max_length=100),
        ),
    ]
