# Generated by Django 4.1.3 on 2022-11-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ui', '0002_customuserdata_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserdata',
            name='challenge_answer_1',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='customuserdata',
            name='challenge_answer_2',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='customuserdata',
            name='challenge_answer_3',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuserdata',
            name='challenge_question_1',
            field=models.CharField(choices=[('what street did you grow up on?', 'What street did you grow up on?'), ("what was your first pet's name?", "What was your first pet's name?"), ("what is your mom's maiden name?", "What is your mom's maiden name?"), ('what high school did you attend?', 'What high school did you attend?'), ('what was the name of the boy or girl you first kissed?', 'What was the name of the boy or girl you first kissed?'), ('what was the first concert you attended?', 'What was the first concert you attended?'), ("what is your oldest sibling's middle name?", "What is your oldest sibling's middle name?"), ('what was the name of your first stuffed toy?', 'What was the name of your first stuffed toy?'), ('where did you meet your spouse?', 'Where did you meet your spouse?'), ('what was the make of your first car?', 'What was the make of your first car?')], max_length=200),
        ),
        migrations.AlterField(
            model_name='customuserdata',
            name='challenge_question_2',
            field=models.CharField(choices=[('what street did you grow up on?', 'What street did you grow up on?'), ("what was your first pet's name?", "What was your first pet's name?"), ("what is your mom's maiden name?", "What is your mom's maiden name?"), ('what high school did you attend?', 'What high school did you attend?'), ('what was the name of the boy or girl you first kissed?', 'What was the name of the boy or girl you first kissed?'), ('what was the first concert you attended?', 'What was the first concert you attended?'), ("what is your oldest sibling's middle name?", "What is your oldest sibling's middle name?"), ('what was the name of your first stuffed toy?', 'What was the name of your first stuffed toy?'), ('where did you meet your spouse?', 'Where did you meet your spouse?'), ('what was the make of your first car?', 'What was the make of your first car?')], max_length=200),
        ),
        migrations.AlterField(
            model_name='customuserdata',
            name='challenge_question_3',
            field=models.CharField(choices=[('what street did you grow up on?', 'What street did you grow up on?'), ("what was your first pet's name?", "What was your first pet's name?"), ("what is your mom's maiden name?", "What is your mom's maiden name?"), ('what high school did you attend?', 'What high school did you attend?'), ('what was the name of the boy or girl you first kissed?', 'What was the name of the boy or girl you first kissed?'), ('what was the first concert you attended?', 'What was the first concert you attended?'), ("what is your oldest sibling's middle name?", "What is your oldest sibling's middle name?"), ('what was the name of your first stuffed toy?', 'What was the name of your first stuffed toy?'), ('where did you meet your spouse?', 'Where did you meet your spouse?'), ('what was the make of your first car?', 'What was the make of your first car?')], max_length=200),
        ),
    ]
